// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Me_7NoH4x7Rwm7qKojXe1POm0Bvk1So',
    appId: '1:979989856312:web:5879c462ce4055957b66cd',
    messagingSenderId: '979989856312',
    projectId: 'yositham',
    authDomain: 'yositham.firebaseapp.com',
    storageBucket: 'yositham.firebasestorage.app',
    measurementId: 'G-4HEG9ZVR2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnFlaoYhFYyKclwMMqVkIIY5W1_MDxa4',
    appId: '1:979989856312:android:a2361589186b853c7b66cd',
    messagingSenderId: '979989856312',
    projectId: 'yositham',
    storageBucket: 'yositham.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3Tn7hp3F55GWAegoyMkgbXevzigvtyo',
    appId: '1:979989856312:ios:f87779f0da6cb5a77b66cd',
    messagingSenderId: '979989856312',
    projectId: 'yositham',
    storageBucket: 'yositham.firebasestorage.app',
    iosBundleId: 'com.restaurant.owner.restaurantApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3Tn7hp3F55GWAegoyMkgbXevzigvtyo',
    appId: '1:979989856312:ios:f87779f0da6cb5a77b66cd',
    messagingSenderId: '979989856312',
    projectId: 'yositham',
    storageBucket: 'yositham.firebasestorage.app',
    iosBundleId: 'com.restaurant.owner.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Me_7NoH4x7Rwm7qKojXe1POm0Bvk1So',
    appId: '1:979989856312:web:23bb893f67990fa87b66cd',
    messagingSenderId: '979989856312',
    projectId: 'yositham',
    authDomain: 'yositham.firebaseapp.com',
    storageBucket: 'yositham.firebasestorage.app',
    measurementId: 'G-EHW2PR70DY',
  );
}
